spring:
  #开启restful风格请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/yupi?rewriteBatchedStatements=true
    username: root
    password: andyfys
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      aop-patterns: "com.andyfys.*"
  aop:
    auto: false
 #设置session的过期时间，这里设置为了一天，单位为秒
  session:
    timeout: 86400

# 配置mybatis规则
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml #指定mapper.xml的位置
#  configuration:
#    map-underscore-to-camel-case: true     # 驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #由于数据库中的格式为驼峰方式，而mybatisplus会自动的为我们转换这个格式，从而产生报错，正常的方式下不需要进行设置
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8080
  servlet:
    context-path: /api